### ISSUE TITLE
compile a newest stripper: source

### ISSUE THREAD

**Issue by ececleon** [alliedmodders/stripper-source#8]
Can you compile a newest stripper: source for me? I do not know why I have been unable to compile.
maybe you can help me

**Comment by ececleon** [comment]
i already install AMBuild,but when i was running AMBuildScript to compile this project,i met problem:

my OS : Ubuntu 16.04.2 LTS
my compile problem : 
ubuntu@VM-54-156-ubuntu:~/stripper-source$ sudo python AMBuildScript
Traceback (most recent call last):
  File "AMBuildScript", line 441, in <module>
    stripper = Stripper()
  File "AMBuildScript", line 65, in __init__
    if AMBuild.mode == 'config':
NameError: global name 'AMBuild' is not defined
ubuntu@VM-54-156-ubuntu:~/stripper-source$ sudo python AMBuildScript
Traceback (most recent call last):
  File "AMBuildScript", line 441, in <module>
    stripper = Stripper()
  File "AMBuildScript", line 65, in __init__
    if AMBuild.mode == 'config':
NameError: global name 'AMBuild' is not defined
ubuntu@VM-54-156-ubuntu:~/stripper-source$ sudo python AMBuildScript
Traceback (most recent call last):
  File "AMBuildScript", line 443, in <module>
    stripper = Stripper()
  File "AMBuildScript", line 67, in __init__
    if AMBuild.mode == 'config':
NameError: global name 'AMBuild' is not defined


Thank you !

**Comment by asherkin** [comment]
You are not using AMBuild correctly, you need to run `configure.py`.

**Comment by ececleon** [comment]
i run configure.py but i meet similar problem

ubuntu@VM-54-156-ubuntu:~/stripper-source$ sudo python configure.py
Traceback (most recent call last):
  File "configure.py", line 10, in <module>
    run.Configure(sys.path[0])
  File "/usr/local/lib/python2.7/dist-packages/ambuild/runner.py", line 113, in Configure
    self.LoadFile(os.path.join(self.sourceFolder, 'AMBuildScript'))
  File "/usr/local/lib/python2.7/dist-packages/ambuild/runner.py", line 137, in LoadFile
    _execfile(path, globals)
  File "/usr/local/lib/python2.7/dist-packages/ambuild/runner.py", line 12, in _execfile
    exec(compile(open(file).read(), file, 'exec'), globals)
  File "/home/ubuntu/stripper-source/AMBuildScript", line 439, in <module>
    stripper = Stripper()
  File "/home/ubuntu/stripper-source/AMBuildScript", line 11, in __init__
    self.compiler = cpp.Compiler()
NameError: global name 'cpp' is not defined

my AMBuild looks like did not install error
ubuntu@VM-54-156-ubuntu:~$ mkdir new
ubuntu@VM-54-156-ubuntu:~$ cd new/
ubuntu@VM-54-156-ubuntu:~/new$ ambuild --new-project
Sample AMBuildScript and configure.py scripts generated.
ubuntu@VM-54-156-ubuntu:~/new$ ls
AMBuildScript  configure.py


thank you~

**Comment by kchr** [comment]
@ececleon Make sure that you have all external build dependencies installed on your system. You can follow this guide for getting the necessary Linux packages: https://wiki.alliedmods.net/Building_SourceMod#Linux

**Comment by kchr** [comment]
@ececleon Also, drop the `sudo`. Never build/compile code that you have not written yourself as the root user.
